### ISSUE TITLE
Collaboration?

### ISSUE THREAD

**Issue by SelfhostedPro** [yangkghjh/selfhosted_store#2]
I'm working on a GUI for creating a variety of templates (from scratch or by importing a current template) here: https://github.com/SelfhostedPro/Yacht-Designer if you would like to collaborate.

**Comment by SelfhostedPro** [comment]
My discord server is here and feel free to pm me: https://discord.gg/KpKutvC

**Comment by SelfhostedPro** [comment]
I was planning on doing all of the conversion via javascript so there's no need for a backend. If not, no worries. Just wanted to reach out about it. Great work! Love the template.

**Comment by yangkghjh** [comment]
I'm happy to collaborate. This project is due to create a tool that can help other projects or users generate their own self hosted app store by several yaml and markdown files. I build the converter with go because by using the docker cli project to parse the `docker-compose.yml` could save a lot of work. I think we can have some discussions to make the cooperation work.

**Comment by SelfhostedPro** [comment]
That sounds great! What's the best way to get in touch? I've done some manual docker-compose parsing which should help speed things up if we need to manually do it.

**Comment by yangkghjh** [comment]
I will join your discord channel. My nickname is biny . I am on a business trip now. So just leave messages on it. I will reply later.
